### ISSUE TITLE
Question about dataset 'Tmall'

### ISSUE THREAD

**Issue by ZorrowHu** [CCIIPLab/GCE-GNN#1]
Thanks for sharing this awesome project! In the RecSys work, https://github.com/andrebola/session-rec-effect, the information about dataset 'Tmall' is inconsistent with that in your paper. And you didn't provide a code to prepare the dataset. So I want to know how that inconsistency exists and hopefully you can provide a guidance in README to help evaluate this project on the Tmall dataset. Great thanks in advance!

**Comment by Mikrokosmos1997** [comment]
Thank you for your attention. In the paper, we omitted some preprocessing operation descriptions for Tmall datasets.  Due to the excessive number of items, we only used the first 120,000 sessions in the original data and filtered those sessions that were longer than 40, which makes the information about our Tmall datasets inconsistent with that in RecSys.

**Comment by xiaxin1998** [comment]
Hi @ZorrowHu  Do you find the right way to reproduce the dataset in this work? Would you mind share the preprocessed Tmall datasets for us? We will appreciate for it! Thanks.
